apiVersion: v2
name: loki
version: 1.0.0
description: "Wrapper chart for Grafana Loki"

dependencies:
  - name: loki
    version: "9.3.0"
    repository: "https://grafana-community.github.io/helm-charts"
