apiVersion: v2
name: vault
description: HashiCorp Vault for secret management in homelab
type: application
version: 0.1.0
appVersion: "1.15.2"

dependencies:
  - name: vault
    version: 0.27.0
    repository: https://helm.releases.hashicorp.com