apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: homelab-subnet-router
spec:
  hostname: homelab-subnet-router
  proxyClass: macmini-pinned
  tags:
    - "tag:homelab"
  subnetRouter:
    advertiseRoutes:
      - "192.168.88.0/24"
