apiVersion: v1
kind: Service
metadata:
  name: home-dns
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: home-dns
spec:
  type: ClusterIP
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: home-dns
  labels:
    kubernetes.io/service-name: home-dns
addressType: IPv4
ports:
  - name: dns-udp
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
endpoints:
  - addresses:
      - "192.168.88.1"
    conditions: {}
