{{- if .Values.externalSecret.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "authelia.fullname" . }}-external-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authelia.labels" . | nindent 4 }}
    app.kubernetes.io/component: external-secret
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.vault.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ include "authelia.fullname" . }}-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: jwt_secret
    remoteRef:
      key: {{ .Values.vault.secretPath }}
      property: jwt_secret
  - secretKey: session_secret
    remoteRef:
      key: {{ .Values.vault.secretPath }}
      property: session_secret
  - secretKey: storage_encryption_key
    remoteRef:
      key: {{ .Values.vault.secretPath }}
      property: storage_encryption_key
  - secretKey: oidc_hmac_secret
    remoteRef:
      key: {{ .Values.vault.secretPath }}
      property: oidc_hmac_secret
  - secretKey: immich_oidc_client_secret
    remoteRef:
      key: {{ .Values.vault.secretPath }}
      property: immich_oidc_client_secret
  - secretKey: oidc_jwks_key
    remoteRef:
      key: {{ .Values.vault.secretPath }}
      property: oidc_jwks_key
  - secretKey: admin_password
    remoteRef:
      key: {{ .Values.vault.secretPath }}
      property: admin_password
  - secretKey: users_database.yml
    remoteRef:
      key: {{ .Values.vault.secretPath }}
      property: users_database
{{- end }}