{{- if .Values.preInstall.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "authelia.fullname" . }}-secret-generator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authelia.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret-generator
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-15"
    "helm.sh/hook-delete-policy": before-hook-creation
automountServiceAccountToken: true
{{- end }}