{{- if .Values.preInstall.enabled }}
---
# Copy Vault root token to authelia namespace for pre-install job
apiVersion: v1
kind: Secret
metadata:
  name: vault-root-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authelia.labels" . | nindent 4 }}
    app.kubernetes.io/component: vault-token
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  root-token: {{ (lookup "v1" "Secret" "vault" "vault-unseal-keys").data.root-token }}
{{- end }}