# Wrapper chart for alloy
# Defaults here, environment-specific overrides in values/homelab.yaml

alloy:
  controller:
    type: daemonset

  alloy:
    # Mount /var/log for pod logs
    mounts:
      varlog: true

    resources:
      requests:
        memory: 856Mi
        cpu: 100m
      limits:
        memory: 1843Mi
        cpu: 1000m
