apiVersion: v2
name: zigbee2mqtt
version: 1.0.0
description: "Wrapper chart for Zigbee2MQTT"

dependencies:
  - name: zigbee2mqtt
    version: "2.9.1"
    repository: "https://charts.zigbee2mqtt.io/"
  - name: common
    version: "0.1.0"
    repository: "file://../common"
