apiVersion: v2
name: blackbox-exporter
version: 1.0.0
description: "Wrapper chart for prometheus-blackbox-exporter"

dependencies:
  - name: prometheus-blackbox-exporter
    version: "11.9.1"
    repository: "https://prometheus-community.github.io/helm-charts"
