apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gamja
  namespace: irc
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: homelab
      namespace: kgateway-system
      sectionName: https
  hostnames:
    - irc.pavlenko.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: gamja
          port: 8081
          weight: 1
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: gamja-auth
  namespace: irc
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: gamja
  extAuth:
    extensionRef:
      name: authelia
      namespace: kgateway-system
