# cert-manager configuration for OrbStack cluster

# Install CRDs via Helm
crds:
  enabled: true

# Enable the default issuer
ingressShim:
  defaultIssuerName: letsencrypt-prod
  defaultIssuerKind: ClusterIssuer
  defaultIssuerGroup: cert-manager.io

# Prometheus monitoring (disabled for now - no Prometheus Operator installed)
prometheus:
  enabled: false

# Resource limits for single-node cluster
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 32Mi

webhook:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 32Mi

cainjector:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 32Mi

# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# Extra objects - ExternalSecret for Cloudflare API token
extraObjects:
  - |
    apiVersion: external-secrets.io/v1
    kind: ExternalSecret
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    spec:
      refreshInterval: 1h
      secretStoreRef:
        name: vault-backend
        kind: ClusterSecretStore
      target:
        name: cloudflare-api-token
        creationPolicy: Owner
        template:
          type: Opaque
          data:
            api-token: "{{ .apiToken }}"
      data:
      - secretKey: apiToken
        remoteRef:
          key: cloudflare
          property: api-token
          conversionStrategy: Default
          decodingStrategy: None
          metadataPolicy: None