# Cilium CNI configuration for homelab cluster

# Enable Hubble for network observability
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
    service:
      type: NodePort
      nodePort: 30080
    ingress:
      enabled: false
  metrics:
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - icmp
      - http

# Enable service mesh capabilities
serviceMonitor:
  enabled: false  # Will enable when we deploy Prometheus

# Network policies
policyEnforcementMode: "default"

# Enable cluster mesh for future multi-cluster setup
clustermesh:
  useAPIServer: false

# Resource configuration for single-node cluster
resources:
  limits:
    memory: 500Mi
  requests:
    memory: 256Mi

# Enable socket LB for better service load balancing
socketLB:
  enabled: true

# Enable bandwidth manager
bandwidthManager:
  enabled: true
  bbr: true

# Enable local redirect policy
localRedirectPolicy: true

# Operator resource limits for single-node cluster
operator:
  # CRITICAL: Single replica to avoid hostPort conflicts on single node
  replicas: 1
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 128Mi
  # Pod anti-affinity prevents multiple replicas on same node anyway
  # but setting replicas=1 avoids the conflict entirely