# Cilium CNI configuration for single-node OrbStack cluster

# CRITICAL: Single-node specific configurations
kubeProxyReplacement: "true"  # Enable for better observability and performance
k8sServiceHost: "198.19.249.2"  # OrbStack node IP
k8sServicePort: "6443"

# Disable IPv6 completely to avoid DNS issues
ipv6:
  enabled: false

# Single-node networking optimizations
tunnel: "vxlan"
autoDirectNodeRoutes: false  # Disable for single-node
endpointRoutes:
  enabled: false  # Not needed for single-node

# Enable Hubble for network observability
hubble:
  enabled: true
  metrics:
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - icmp
      - http
      - port-distribution
      - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction
    serviceMonitor:
      enabled: false  # Will enable when we deploy Prometheus
  relay:
    enabled: true
    rollOutPods: true
  ui:
    enabled: true
    rollOutPods: true
    service:
      type: NodePort
      nodePort: 30080
    ingress:
      enabled: false

# Enable socket LB for better service load balancing
socketLB:
  enabled: true

# Enable bandwidth manager
bandwidthManager:
  enabled: true
  bbr: true

# Enable local redirect policy
localRedirectPolicy: true

# Resource configuration for single-node cluster
resources:
  limits:
    memory: 500Mi
  requests:
    memory: 256Mi

# Network policies - start permissive for troubleshooting
policyEnforcementMode: "default"

# Single-node cluster optimizations
nodePort:
  enabled: true  # Enable NodePort for single-node access

# Enable health checking
healthChecking: true

# Disable cluster mesh for single-node
clustermesh:
  useAPIServer: false

# Operator resource limits for single-node cluster
operator:
  # CRITICAL: Single replica to avoid hostPort conflicts on single node
  replicas: 1
  # Update strategy to prevent multiple pods during rolling updates
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0        # Never create extra pods
      maxUnavailable: 1  # Allow 1 pod to be unavailable during update
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 128Mi