# Cilium CNI configuration for single-node K3d cluster

# Enable kube-proxy replacement
kubeProxyReplacement: true

# Ingress Controller configuration
ingressController:
  enabled: true
  default: true

# Gateway API support
gatewayAPI:
  enabled: true

# IPAM configuration
ipam:
  mode: kubernetes
  operator:
    clusterPoolIPv4PodCIDRList:
      - "10.42.0.0/16"

# Single node setup - ensure only 1 operator
operator:
  replicas: 1

# Hubble configuration for network observability
hubble:
  enabled: true
  ui:
    enabled: true
    service:
      type: ClusterIP
