# Cilium CNI configuration for K3s cluster

# IPAM configuration with cluster pool
ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
      - "10.42.0.0/16"

# Hubble configuration for network observability
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
    service:
      type: NodePort
      nodePort: 30080
  metrics:
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http
