# ArgoCD configuration for homelab cluster

# Server configuration
server:
  service:
    type: NodePort
    nodePortHttp: 30081
    nodePortHttps: 30443
  
  # Disable internal TLS for simplicity in local setup
  insecure: true
  
  # ArgoCD configuration
  config:
    # Enable anonymous access for easier setup (can be disabled later)
    url: "http://localhost:30081"
    
    # Git repositories configuration
    repositories: |
      - type: git
        url: https://github.com/pavlenkoa/homelab.git
        name: homelab
    
    # Resource customizations
    resource.customizations: |
      argoproj.io/Application:
        health.lua: |
          hs = {}
          hs.status = "Progressing"
          hs.message = ""
          if obj.status ~= nil then
            if obj.status.health ~= nil then
              hs.status = obj.status.health.status
              if obj.status.health.message ~= nil then
                hs.message = obj.status.health.message
              end
            end
          end
          return hs

# Controller configuration
controller:
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi

# Repo server configuration  
repoServer:
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 128Mi

# Application set controller
applicationSet:
  enabled: true
  resources:
    limits:
      memory: 128Mi
    requests:
      memory: 64Mi

# Notifications controller
notifications:
  enabled: false  # Can enable later for alerting

# Redis configuration
redis:
  resources:
    limits:
      memory: 128Mi
    requests:
      memory: 64Mi