# Homelab environment values for Authelia

# Vault configuration for homelab
vault:
  address: "http://vault.vault.svc.cluster.local:8200"
  secretPath: "kv/authelia"
  secretStoreName: "vault-backend"

# Admin user configuration
preInstall:
  adminUser:
    displayName: "Homelab Administrator"
    email: "admin@pavlenko.io"

# Override upstream chart values for homelab
authelia:
  # Ingress configuration for pavlenko.io
  ingress:
    enabled: true
    className: 'nginx'
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    rulesOverride:
      - host: 'auth.pavlenko.io'
        path: '/'
    tls:
      enabled: true
      secret: 'authelia-tls'
      hostNameOverride: 'auth.pavlenko.io'
  
  # Override access control rules for homelab domains
  configMap:
    access_control:
      default_policy: 'deny'
      rules:
        - domain: 'test.pavlenko.io'
          policy: 'two_factor'
        - domain: 'transmission.pavlenko.io'
          policy: 'two_factor'
        - domain: 'photos.pavlenko.io'
          policy: 'two_factor'
        - domain: 'emby.pavlenko.io'
          policy: 'two_factor'

  # Resource configuration for homelab
  pod:
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
  
  # Redis configuration
  redis:
    master:
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"
          cpu: "100m"
