# Homelab environment values for Authelia

# Vault configuration for homelab
vault:
  address: "http://vault.vault.svc.cluster.local:8200"
  secretPath: "kv/authelia"
  secretStoreName: "vault-backend"

# Admin user configuration
preInstall:
  adminUser:
    displayName: "Homelab Administrator"
    email: "admin@pavlenko.io"

# Override upstream chart values for homelab
authelia:
  # Ingress configuration for pavlenko.io
  ingress:
    enabled: true
    className: 'nginx'
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    rulesOverride:
      - host: 'auth.pavlenko.io'
        path: '/'
    tls:
      enabled: true
      secret: 'authelia-tls'
      hostNameOverride: 'auth.pavlenko.io'

  # Main configuration overrides  
  configMap:
    theme: 'dark'
    default_2fa_method: 'webauthn'


    identity_validation:
      reset_password:
        jwt_lifespan: '5 minutes'
        jwt_algorithm: 'HS256'
        ## The secret used with the HMAC algorithm to sign the JWT minted by Authelia.
        secret:
          disabled: false
          secret_name: 'authelia-secrets'
          path: 'jwt_secret'

    # Authentication backend using file
    authentication_backend:
      file:
        enabled: true
        path: '/secrets/authelia-secrets/users_database'

    # Storage configuration
    storage:
      encryption_key:
        disabled: false
        secret_name: 'authelia-secrets'
        path: 'storage_encryption_key'
      local:
        enabled: true
        path: '/config/db.sqlite3'
    
    # Session configuration
    session:
      encryption_key:
        disabled: false
        secret_name: 'authelia-secrets'
        path: 'session_secret'
      cookies:
        - name: 'authelia_session'
          domain: 'pavlenko.io'
          authelia_url: 'https://auth.pavlenko.io'
          default_redirection_url: 'https://test.pavlenko.io'
          expiration: '3600'
          inactivity: '300'
      redis:
        enabled: true
        host: 'authelia-redis'
        port: 6379
        database_index: 0
        password:
          disabled: false
          secret_name: 'authelia-secrets'
          path: 'redis_password'
    
    # Notification configuration  
    notifier:
      filesystem:
        enabled: true
        filename: '/config/notification.txt'
    # Access control rules for homelab domains
    access_control:
      default_policy: 'deny'
      rules:
        - domain: 'test.pavlenko.io'
          policy: 'two_factor'
        - domain: 'transmission.pavlenko.io'
          policy: 'two_factor'
        - domain: 'photos.pavlenko.io'
          policy: 'two_factor'
        - domain: 'emby.pavlenko.io'
          policy: 'two_factor'
    
    # OIDC clients for homelab services
    identity_providers:
      oidc:
        enabled: true
        hmac_secret:
          disabled: false
          secret_name: 'authelia-secrets'
          path: 'oidc_hmac_secret'
        jwks:
          - key_id: 'main-signing-key'
            algorithm: 'RS256'
            use: 'sig'
            key_file: '/secrets/authelia-secrets/oidc_jwks_key'
        clients:
          - client_id: 'immich'
            client_name: 'Immich Photos'
            client_secret_file: '/secrets/authelia-secrets/immich_oidc_client_secret'
            public: false
            authorization_policy: 'two_factor'
            redirect_uris:
              - 'https://photos.pavlenko.io/auth/login'
              - 'https://photos.pavlenko.io/user-settings'
              - 'app.immich:///oauth-callback'
            scopes:
              - 'openid'
              - 'profile'
              - 'email'
            userinfo_signed_response_alg: 'none'
            token_endpoint_auth_method: 'client_secret_post'

  # Resource configuration for homelab
  pod:
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
  
  # Redis configuration
  redis:
    master:
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"
          cpu: "100m"
