# Homelab environment values for Authelia

# Vault configuration for homelab
vault:
  address: "http://vault.vault.svc.cluster.local:8200"
  secretPath: "homelab/authelia"
  secretStoreName: "vault-backend"

# Admin user configuration
preInstall:
  adminUser:
    displayName: "Homelab Administrator"
    email: "admin@pavlenko.io"

# Override upstream chart values for homelab
authelia:
  # Ingress configuration for pavlenko.io
  ingress:
    enabled: true
    className: 'nginx'
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    rulesOverride:
      - host: 'auth.pavlenko.io'
        path: '/'
    tls:
      enabled: true
      secret: 'authelia-tls'
      hostNameOverride: 'auth.pavlenko.io'
  
  # Main configuration overrides
  configMap:
    # Access control rules for homelab domains
    access_control:
      default_policy: 'deny'
      rules:
        - domain: 'test.pavlenko.io'
          policy: 'two_factor'
        - domain: 'transmission.pavlenko.io'
          policy: 'two_factor'
        - domain: 'photos.pavlenko.io'
          policy: 'two_factor'
        - domain: 'emby.pavlenko.io'
          policy: 'two_factor'
    
    # Session configuration for pavlenko.io domain
    session:
      cookies:
        - name: 'authelia_session'
          domain: 'pavlenko.io'
          authelia_url: 'https://auth.pavlenko.io'
          default_redirection_url: 'https://test.pavlenko.io'
          expiration: '3600'
          inactivity: '300'
    
    # OIDC clients for homelab services
    identity_providers:
      oidc:
        enabled: true
        clients:
          - client_id: 'immich'
            client_name: 'Immich Photos'
            client_secret:
              secret_name: 'authelia-secrets'
              path: 'immich_oidc_client_secret'
            public: false
            authorization_policy: 'two_factor'
            redirect_uris:
              - 'https://photos.pavlenko.io/auth/login'
              - 'https://photos.pavlenko.io/user-settings'
              - 'app.immich:///oauth-callback'
            scopes:
              - 'openid'
              - 'profile'
              - 'email'
            userinfo_signed_response_alg: 'none'
            token_endpoint_auth_method: 'client_secret_post'

  # Resource configuration for homelab
  pod:
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
  
  # Redis configuration
  redis:
    master:
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"
          cpu: "100m"