# External Secrets Operator configuration for homelab

# Install CRDs via Helm  
crds:
  create: true

# Concurrent secret fetches
concurrent: 3

# Resource limits for single-node cluster
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 32Mi

webhook:
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 16Mi

certController:
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 16Mi

# Security context
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534
  seccompProfile:
    type: RuntimeDefault

# Pod security context  
podSecurityContext:
  fsGroup: 65534

# Monitoring (disabled for now)
serviceMonitor:
  enabled: false

# Extra objects - ClusterSecretStore for Vault backend (temporarily disabled for CRD timing)
extraObjects: []
  # - |
  #   apiVersion: external-secrets.io/v1beta1
  #   kind: ClusterSecretStore
  #   metadata:
  #     name: vault-backend
  #   spec:
  #     provider:
  #       vault:
  #         server: "http://vault.vault.svc.cluster.local:8200"
  #         path: "kv"
  #         version: "v2"
  #         auth:
  #           kubernetes:
  #             mountPath: "kubernetes"
  #             role: "external-secrets"
  #             serviceAccountRef:
  #               name: "external-secrets"
  #               namespace: "external-secrets"