# HashiCorp Vault Complete configuration for homelab
# This includes Vault server + auto-unseal capabilities

# Auto-unseal configuration
autoUnseal:
  enabled: true
  
  # RBAC configuration
  rbac:
    create: true
    serviceAccountName: "vault-auto-unseal"
  
  # Initialization job configuration
  initJob:
    enabled: true
    image: "hashicorp/vault:1.15.2"
    
  # Auto-unseal CronJob configuration  
  cronJob:
    enabled: true
    schedule: "*/5 * * * *"  # Every 5 minutes
    image: "hashicorp/vault:1.15.2"

# Vault subchart configuration
vault:
  # Global configuration
  global:
    enabled: true

  # Server configuration
  server:
    # Disable development mode for production setup with auto-unseal
    dev:
      enabled: false
    
    # Single instance for homelab with persistent storage
    standalone:
      enabled: true
      config: |
        ui = true

        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          # Enable unauthenticated metrics access (necessary for Prometheus Operator)
          telemetry {
            unauthenticated_metrics_access = "true"
          }
        }
        
        storage "file" {
          path = "/vault/data"
        }

        # Telemetry for monitoring
        telemetry {
          prometheus_retention_time = "30s"
          disable_hostname = true
        }

    # ClusterIP service (will use ingress later)
    service:
      type: ClusterIP
      port: 8200

    # Data storage (required for standalone mode)
    dataStorage:
      enabled: true
      size: 2Gi
      storageClass: null
      accessMode: ReadWriteOnce
    
    # Simple postStart hook for basic unsealing (backup to CronJob)
    postStart:
      - sh
      - -c
      - |
        # Simple unseal attempt on container start
        sleep 5
        if vault status 2>/dev/null | grep -q "Sealed.*true"; then
          echo "Vault is sealed, will be handled by auto-unseal job"
        fi

    # Resource limits for single-node cluster
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 500m

    # Readiness and liveness probes
    readinessProbe:
      enabled: true
      path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
    livenessProbe:
      enabled: true
      path: "/v1/sys/health?standbyok=true"
      initialDelaySeconds: 60

    # Service account with RBAC permissions for managing secrets
    serviceAccount:
      create: false  # We'll use the custom service account with RBAC
      name: "vault-auto-unseal"

  # UI configuration
  ui:
    enabled: true
    serviceType: "ClusterIP"

  # Injector configuration (for secret injection)
  injector:
    enabled: true
    
    # Resource limits for injector
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 128Mi
        cpu: 250m

    # Agent configuration for sidecar injection
    agentImage:
      repository: "hashicorp/vault"
      tag: "1.15.2"

  # CSI driver (optional for homelab)
  csi:
    enabled: false