# RBAC configuration for Vault auto-unseal
# This creates the necessary permissions for Vault to manage its own unseal keys

apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auto-unseal
  namespace: vault
  annotations:
    vault.hashicorp.com/auto-unseal: "true"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: vault
  name: vault-auto-unseal
rules:
  # Allow Vault to manage secrets in its own namespace
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  # Allow Vault to read its own service account
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-auto-unseal
  namespace: vault
subjects:
  - kind: ServiceAccount
    name: vault-auto-unseal
    namespace: vault
roleRef:
  kind: Role
  name: vault-auto-unseal
  apiGroup: rbac.authorization.k8s.io