---
services:
  alloy:
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro

  mikrotik_exporter:
    container_name: mikrotik_exporter
    image: ghcr.io/akpw/mktxp:main
    restart: unless-stopped
    user: root
    expose:
      - 49090
    volumes:
      - ${PWD}/monitoring/mikrotik/config:/root/mktxp/
    networks:
      - monitoring_network

  transmission_exporter:
    container_name: transmission_exporter
    image: transmission-exporter:local
    restart: unless-stopped
    expose:
      - 19091
    environment:
      - TRANSMISSION_ADDR=${TRANSMISSION_ADDR}
      - WEB_ADDR=${WEB_ADDR}
      - WEB_PATH=${WEB_PATH}
    networks:
      - monitoring_network