apiVersion: v1
kind: ConfigMap
metadata:
  name: soju-config
  namespace: irc
data:
  soju.cfg: |
    hostname irc.pavlenko.io
    title "pavlenko.io IRC"
    listen ws+insecure://0.0.0.0:8080
    listen unix+admin:///var/run/soju/admin.sock
    db sqlite3 /data/main.db
    message-store db
    http-origin "https://irc.pavlenko.io"
