apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: soju-bootstrap
  namespace: irc
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: soju-bootstrap
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: admin_password
      remoteRef:
        key: soju
        property: admin_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
