apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayExtension
metadata:
  name: authelia
spec:
  type: ExtAuth
  extAuth:
    httpService:
      backendRef:
        name: authelia
        namespace: authelia
        port: 80
      pathPrefix: /api/authz/ext-authz/
      authorizationRequest:
        headersToAdd:
          X-Forwarded-Proto: "%REQ(:SCHEME)%"
          X-Forwarded-Host: "%REQ(:AUTHORITY)%"
      authorizationResponse:
        headersToBackend:
          - Remote-User
          - Remote-Name
          - Remote-Email
          - Remote-Groups
    headersToForward:
      - cookie
