apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kgateway-basic-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: kgateway-basic-auth
  data:
    - secretKey: .htpasswd
      remoteRef:
        key: kv/kgateway
        property: htpasswd
