apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayParameters
metadata:
  name: self-managed
spec:
  selfManaged: {}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: kgateway
  infrastructure:
    parametersRef:
      name: self-managed
      group: gateway.kgateway.dev
      kind: GatewayParameters
  listeners:
    - name: http
      protocol: HTTP
      port: {{ .Values.gateway.listeners.http.port }}
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: {{ .Values.gateway.listeners.https.port }}
      hostname: "*.pavlenko.io"
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: homelab-gateway-tls
      allowedRoutes:
        namespaces:
          from: All
