apiVersion: v1
kind: Service
metadata:
  name: kgateway-metrics
  labels:
    app.kubernetes.io/name: kgateway
spec:
  selector:
    app.kubernetes.io/name: kgateway
  ports:
    - port: 9092
      targetPort: 9092
      name: metrics
