{{- if .Values.basicAuth.enabled }}
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: {{ include "victoriametrics-wrapper.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: victoriametrics
  basicAuth:
    secretRef:
      name: {{ .Values.externalSecret.secretName }}
      namespace: {{ .Release.Namespace }}
{{- end }}
