{{- range $serviceName, $serviceConfig := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  labels:
    {{- include "external-services.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $serviceConfig.service.port | default 80 }}
      targetPort: {{ $serviceConfig.endpoint.port }}
      protocol: TCP
      name: {{ $serviceConfig.endpoint.protocol | default "http" }}
  # No selector - this service will be paired with manually created EndpointSlice
{{- end }}