{{- range $serviceName, $serviceConfig := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  labels:
    {{- include "external-services.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
spec:
  type: ExternalName
  externalName: {{ $serviceConfig.endpoint.host }}
  ports:
    - port: {{ $serviceConfig.endpoint.port }}
      protocol: TCP
      name: {{ $serviceConfig.endpoint.protocol | default "http" }}
{{- end }}