apiVersion: apps/v1
kind: Deployment
metadata:
  name: mktxp
  namespace: monitoring
  labels:
    app: mktxp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mktxp
  template:
    metadata:
      labels:
        app: mktxp
    spec:
      containers:
        - name: mktxp
          image: ghcr.io/akpw/mktxp:main@sha256:428f243fd53f4abc3830e95dc3f36f4b0152e6d2f9d58e0f30748e4fe4e5420d
          ports:
            - containerPort: 49090
              name: metrics
          volumeMounts:
            - name: config
              mountPath: /home/mktxp/mktxp/
              readOnly: true
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 200m
      volumes:
        - name: config
          secret:
            secretName: mktxp-config
