apiVersion: apps/v1
kind: Deployment
metadata:
  name: mktxp
  namespace: monitoring
  labels:
    app: mktxp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mktxp
  template:
    metadata:
      labels:
        app: mktxp
    spec:
      containers:
        - name: mktxp
          image: ghcr.io/akpw/mktxp:main@sha256:16bb62baca6bdd86ea2bb161aca1b152a9063a8fc06e3f10500ece834c3823e3
          ports:
            - containerPort: 49090
              name: metrics
          volumeMounts:
            - name: config
              mountPath: /home/mktxp/mktxp/
              readOnly: true
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 200m
      volumes:
        - name: config
          secret:
            secretName: mktxp-config
