apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mktxp-config
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mktxp-config
    creationPolicy: Owner
    template:
      data:
        mktxp.conf: |
          [wroclaw-hap-ax2]
              hostname = 192.168.88.1
              username = {{ `{{ .username }}` }}
              password = {{ `{{ .password }}` }}

          [default]
              enabled = True
              module_only = False
              port = 8728
              plaintext_login = True

              use_ssl = False
              no_ssl_certificate = False
              ssl_certificate_verify = False
              ssl_check_hostname = True
              ssl_ca_file = ""
              credentials_file = ""
              custom_labels = None

              health = True
              installed_packages = True
              dhcp = True
              dhcp_lease = True
              connections = True
              connection_stats = False
              interface = True
              route = True
              pool = True
              firewall = True
              neighbor = True
              address_list = None
              dns = False
              poe = True
              monitor = True
              netwatch = True
              public_ip = True
              wireless = True
              wireless_clients = True
              capsman = True
              capsman_clients = True
              w60g = False
              user = True
              queue = True
              container = False

              ipv6_route = False
              ipv6_pool = False
              ipv6_firewall = False
              ipv6_neighbor = False
              ipv6_address_list = None

              eoip = False
              gre = False
              ipip = False
              lte = False
              ipsec = False
              switch_port = False
              bfd = False
              bgp = False
              routing_stats = False
              certificate = False

              kid_control_assigned = False
              kid_control_dynamic = False

              remote_dhcp_entry = None
              remote_capsman_entry = None
              interface_name_format = name
              check_for_updates = False
        _mktxp.conf: |
          [MKTXP]
              listen = '0.0.0.0:49090'
              socket_timeout = 5

              initial_delay_on_failure = 120
              max_delay_on_failure = 900
              delay_inc_div = 5

              bandwidth = False
              bandwidth_test_dns_server = 8.8.8.8
              bandwidth_test_interval = 600
              minimal_collect_interval = 5

              verbose_mode = False

              fetch_routers_in_parallel = False
              max_worker_threads = 5
              max_scrape_duration = 30
              total_max_scrape_duration = 90
              http_server_threads = 16

              persistent_router_connection_pool = True
              persistent_dhcp_cache = True
              compact_default_conf_values = False
              prometheus_headers_deduplication = False

              probe_connection_pool = False
              probe_connection_pool_ttl = 300
              probe_connection_pool_max_size = 128
  data:
    - secretKey: username
      remoteRef:
        key: kv/monitoring/mikrotik
        property: username
    - secretKey: password
      remoteRef:
        key: kv/monitoring/mikrotik
        property: password
