apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbit-throttle-emby
  namespace: qbittorrent
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: qbit-throttle-emby
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: EMBY_API_KEY
      remoteRef:
        key: emby
        property: api_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
