apiVersion: v2
name: vault-complete
description: Complete HashiCorp Vault deployment with auto-unseal for homelab
type: application
version: 0.1.0
appVersion: "1.15.2"

dependencies:
  - name: vault
    version: "0.27.0"
    repository: "https://helm.releases.hashicorp.com"