{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "loki-wrapper.fullname" . }}-basic-auth
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.vault.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecret.secretName }}
    creationPolicy: Owner
    template:
      data:
        .htpasswd: "promtail:{{ `{{ .push_password_hash }}` }}"
  data:
    - secretKey: push_password_hash
      remoteRef:
        key: {{ .Values.vault.secretPath }}
        property: push_password_hash
    - secretKey: push_password
      remoteRef:
        key: {{ .Values.vault.secretPath }}
        property: push_password
{{- end }}
