---
services:
  authelia:
    container_name: authelia
    image: authelia/authelia:latest
    restart: unless-stopped
    command: authelia --config /config/configuration.yml
    ports:
      - "9091:9091"
    environment:
      - TZ=${TIMEZONE:-Europe/Warsaw}
    volumes:
      - ${PWD}/authelia/config:/config
      - ${PWD}/authelia/data:/data
    depends_on:
      - redis
    networks:
      - authelia_network

  redis:
    container_name: authelia-redis
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ${PWD}/authelia/redis-data:/data
    networks:
      - authelia_network

networks:
  authelia_network:
    name: authelia_network
