---
services:
  caddy:
    container_name: caddy
    image: caddy:local
    environment:
      - TZ=${TIMEZONE:-Europe/Warsaw}
      - CF_API_TOKEN=${CF_API_TOKEN}
      - BASIC_AUTH_USER=${BASIC_AUTH_USER}
      - BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD}
      - DOMAIN=${DOMAIN_NAME}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${PWD}/caddy/data:/data
      - type: bind
        source: ${PWD}/caddy/config/Caddyfile
        target: /etc/caddy/Caddyfile
        read_only: true
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    name: caddy_network